language: python

python:
    - "2.7"
    - "3.4"
    - "3.5"

install:
    - pip install --upgrade setuptools coveralls
    - python setup.py develop

script:
    - coverage run -m unittest -v

after_success:
    - coveralls
